<a href="https://colab.research.google.com/github/Uncle-Solomon/NeuralLearnTutorials/blob/main/Neuralearn_Intro_to_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2, 0,-3, 4, 5, 2, 11], dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  4.  5.  2. 11.], shape=(7,), dtype=float32)
tf.Tensor([ True False  True  True  True  True  True], shape=(7,), dtype=bool)


In [ ]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["Hello", "World"])
print(tensor_string)

tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [
        [1,2,0],
        [3,5,1]
    ],
    [
        [10,2,0],
        [1, 0, 2]
    ],
    [
        [5, 8, 0],
        [2,7,0]
    ],
    [
        [2,1,9],
        [4,-3,32]
    ]
])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5  1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape, tensor_three_d.dtype, tensor_three_d.ndim)

(4, 2, 3) <dtype: 'int32'> 3


In [ ]:
tensor_four_d = tf.constant([
    [
    [
        [1,2,0],
        [3,5,1]
    ],
    [
        [10,2,0],
        [1, 0, 2]
    ],
    [
        [5, 8, 0],
        [2,7,0]
    ],
    [
        [2,1,9],
        [4,-3,32]
    ]
],
    [
    [
        [1,2,0],
        [3,5,1]
    ],
    [
        [10,2,0],
        [1, 0, 2]
    ],
    [
        [5, 8, 0],
        [2,7,0]
    ],
    [
        [2,1,9],
        [4,-3,32]
    ]
],
    [
    [
        [1,2,0],
        [3,5,1]
    ],
    [
        [10,2,0],
        [1, 0, 2]
    ],
    [
        [5, 8, 0],
        [2,7,0]
    ],
    [
        [2,1,9],
        [4,-3,32]
    ]
],
     [
    [
        [1,2,0],
        [3,5,1]
    ],
    [
        [10,2,0],
        [1, 0, 2]
    ],
    [
        [5, 8, 0],
        [2,7,0]
    ],
    [
        [2,1,9],
        [4,-3,32]
    ]
],

])

print(tensor_four_d, f"Number of dimensions: {tensor_four_d.ndim}")

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5  1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5  1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5  1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5  1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(4, 4, 2, 3), dtype=int32) Number of dimensions: 4


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_to_tensor = tf.convert_to_tensor(np_array)
print(converted_to_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
np_2d_array = np.array([[1,2,3],[4,5,6]])
convert_2d = tf.convert_to_tensor(np_2d_array)
print(convert_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [ ]:
eye_tensor = tf.eye(num_rows=5, num_columns=None, batch_shape=[2,], dtype=tf.dtypes.float32, name=None)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [ ]:
fill_tensor = tf.fill(
    [3, 3,4], 5, name=None
)

print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(3, 3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones([4,2, 3], dtype=tf.dtypes.int32)
print(ones_tensor)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
ones_like_tensor = tf.ones_like(input=fill_tensor, dtype=tf.dtypes.float32)
print(ones_like_tensor)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(3, 3, 4), dtype=float32)


In [ ]:
zeros_tensor = tf.zeros([3,2, 3], dtype=tf.dtypes.int32)
print(zeros_tensor)

tf.Tensor(
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
shape_of_tensor = tf.shape(input=zeros_tensor)
print(shape_of_tensor)

tf.Tensor([3 2 3], shape=(3,), dtype=int32)


In [ ]:
random_tensor = tf.random.normal([2, 3, 4], mean=0.45,stddev=0.1,dtype=tf.dtypes.float32,seed=None,name=None)
print(random_tensor)

tf.Tensor(
[[[0.46566987 0.52860916 0.3911191  0.44431645]
  [0.32794318 0.2544353  0.5408107  0.54326713]
  [0.40170434 0.6972556  0.41668156 0.4931044 ]]

 [[0.40146977 0.34540173 0.5099342  0.5406069 ]
  [0.46402004 0.5087289  0.5282065  0.30937153]
  [0.46432245 0.31236243 0.51284635 0.48709196]]], shape=(2, 3, 4), dtype=float32)


In [ ]:
random_uniform_tensor = tf.random.uniform([2, 3, 4], minval=8, maxval=25 ,dtype=tf.dtypes.float32,seed=None,name=None)
print(random_uniform_tensor)

tf.Tensor(
[[[23.828009  18.651741  19.230637  15.37781  ]
  [12.546459  22.81413   22.868582  12.164106 ]
  [10.30251   23.47546   22.91777   20.523056 ]]

 [[12.357168  10.1074295  8.884741  18.617283 ]
  [ 9.38712   17.755713  21.823004  14.633704 ]
  [21.98029   15.882149  16.238834  20.98468  ]]], shape=(2, 3, 4), dtype=float32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
 tensor_indexed = tf.constant([3,6,2,4,6,66,7])
 print(tensor_indexed)

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)


In [ ]:
print(tensor_indexed[1:-3])

tf.Tensor([6 2 4], shape=(3,), dtype=int32)


In [ ]:
  print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
print(tensor_two_d[0:3, 0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
 print(tensor_two_d[...,0])

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
 print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5  1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
 print(tensor_three_d[:,:,:2])

tf.Tensor(
[[[ 1  2]
  [ 3  5]]

 [[10  2]
  [ 1  0]]

 [[ 5  8]
  [ 2  7]]

 [[ 2  1]
  [ 4 -3]]], shape=(4, 2, 2), dtype=int32)


In [ ]:
x_1 = tf.constant([1, 3, 5, 56, 7, 88, 123, 455, 0, 2], dtype=tf.float32)
x_2 = tf.constant([1, 2, 15, 45, 2, 6, 8, 9 ,0, 2], dtype=tf.float32)

print(tf.math.add(x_1, x_2))

tf.Tensor([  2.   5.  20. 101.   9.  94. 131. 464.   0.   4.], shape=(10,), dtype=float32)


In [ ]:
x_argmax = tf.constant([[2,20,30,3,6], [3,11,16,1,8],[14,45,23,5,27]])

print(x_argmax.shape)
print(tf.math.argmin(x_argmax, axis=0))
print(tf.math.argmin(tensor_four_d, axis=1))

(3, 5)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor(
[[[0 3 0]
  [1 3 2]]

 [[0 3 0]
  [1 3 2]]

 [[0 3 0]
  [1 3 2]]

 [[0 3 0]
  [1 3 2]]], shape=(4, 2, 3), dtype=int64)


In [ ]:
x_argmax = tf.constant([2,20,30,3,6])
print(tf.math.argmax(x_argmax))

tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
x_equal = tf.constant([[2,4], [5,4]], dtype=tf.float32)
y_equal = tf.constant([[2,4], [2,6]], dtype=tf.float32)

print(tf.math.equal(x_equal, y_equal))
print(x_equal.shape, y_equal.shape)

tf.Tensor(
[[ True  True]
 [False False]], shape=(2, 2), dtype=bool)
(2, 2) (2, 2)


In [ ]:
print(x_equal@y_equal)

tf.Tensor(
[[12. 32.]
 [18. 44.]], shape=(2, 2), dtype=float32)


In [ ]:
tf.transpose(x_equal)
tf.transpose(tensor_four_d)


<tf.Tensor: shape=(3, 2, 4, 4), dtype=int32, numpy=
array([[[[ 1,  1,  1,  1],
         [10, 10, 10, 10],
         [ 5,  5,  5,  5],
         [ 2,  2,  2,  2]],

        [[ 3,  3,  3,  3],
         [ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 4,  4,  4,  4]]],


       [[[ 2,  2,  2,  2],
         [ 2,  2,  2,  2],
         [ 8,  8,  8,  8],
         [ 1,  1,  1,  1]],

        [[ 5,  5,  5,  5],
         [ 0,  0,  0,  0],
         [ 7,  7,  7,  7],
         [-3, -3, -3, -3]]],


       [[[ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [ 9,  9,  9,  9]],

        [[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 0,  0,  0,  0],
         [32, 32, 32, 32]]]], dtype=int32)>

In [ ]:
tf.linalg.inv(x_equal)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.33333334,  0.33333334],
       [ 0.4166667 , -0.16666667]], dtype=float32)>

In [ ]:
s, v, d = tf.linalg.svd(x_equal)
print(s)
print(v)
print(d)

tf.Tensor([7.6511536 1.5683912], shape=(2,), dtype=float32)
tf.Tensor(
[[-0.55925715 -0.82899433]
 [-0.82899433  0.55925703]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.68793356  0.72577363]
 [-0.72577363 -0.68793356]], shape=(2, 2), dtype=float32)


In [ ]:
import numpy as np

In [ ]:
A = np.array([[2, 6, 5, 2], [2, -2, 2, 3], [1, 5, 4, 0]])
B  = np.array([[2, 9, 0, 3, 0], [3, 6, 8, -2, 2], [1, 3, 5, 0, 1], [3, 0, 2, 0, 5]])

print(A.shape, B.shape)

print("Matmul C =: \n")
print(np.matmul(A, B), " \n")

print("Dot C =: \n")
print(np.dot(A, B), " \n")

print("Einsum C =: \n")
print(np.einsum("ij,jk->ik", A, B), " \n")

(3, 4) (4, 5)
Matmul C =: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]  

Dot C =: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]  

Einsum C =: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]  



In [ ]:
A = np.array([[2, 6, 5, 2], [2, -2, 2, 3], [1, 5, 4, 0]])
B  = np.array([[2, 9, 0, 3], [3, 6, 8, -2], [1, 3, 5, 0]])

print(A.shape, B.shape)
print("Hadamard Product C =: \n")
print(A * B, " \n")

print("Einsum C =: \n")
print(np.einsum("ij,ij->ij", A, B), " \n")



(3, 4) (3, 4)
Hadamard Product C =: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]  

Einsum C =: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]  



In [ ]:
print("Transpose A =: \n")
print(np.transpose(A), " \n")

print("Einsum Transpose A =: \n")
print(np.einsum("ij -> ji", A), " \n")

Transpose A =: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]  

Einsum Transpose A =: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]  



In [ ]:
q = np.random.randn(32, 64, 512)
k = np.random.randn(32, 128, 512)

product = np.einsum("bqm,bkm->bqk", q, k)


In [ ]:
print(product.shape)
print(tf.expand_dims(product, axis=1).shape)
x_expanded = tf.expand_dims(product, axis=0)
print(x_expanded.shape)

(32, 64, 128)
(32, 1, 64, 128)
(1, 32, 64, 128)


In [ ]:
print(tf.squeeze(x_expanded, axis=0).shape)

(32, 64, 128)


In [ ]:
t1 = tf.constant([[4, 3, 2, 6], [4, 6, 6, -1,]])

tf.reshape(t1, shape=(2, -1))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 4,  3,  2,  6],
       [ 4,  6,  6, -1]], dtype=int32)>

In [ ]:
t = tf.constant([[1,2,3],[4,5,6]])

paddings = tf.constant([[1,1], [2,25]])

tf.pad(t, paddings, "CONSTANT")

<tf.Tensor: shape=(4, 30), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
x = tf.constant([1,2])
x_var = tf.Variable(x, name="var1")
x_var.assign_sub([12, 21])
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([-11, -19], dtype=int32)>


In [ ]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)

print(x_var.device)

/job:localhost/replica:0/task:0/device:GPU:0
